### ISSUE TITLE
Alternative board geometries

### ISSUE THREAD

**Issue by thorsilver** [kervinck/pfkpk#1]
Please forgive my stupid question, but how can I implement a board geometry like the following:

enum square {
    a1, b1, c1, d1, e1, f1, g1, h1,
    a2, b2, c2, d2, e2, f2, g2, h2,
    a3, b3, c3, d3, e3, f3, g3, h3,
    a4, b4, c4, d4, e4, f4, g4, h4,
    a5, b5, c5, d5, e5, f5, g5, h5,
    a6, b6, c6, d6, e6, f6, g6, h6,
    a7, b7, c7, d7, e7, f7, g7, h7,
    a8, b8, c8, d8, e8, f8, g8, h8,
    boardSize
};

And how does this affect the derived geometry definitions in line 52 of kpk.c?

I'm sorry, my geometric education was about 25 years ago and I'm stumped by this for some reason :)  When I try to get this to work, the self-check fails, and kpkProbe fails at 8/26.

**Comment by kervinck** [comment]
There are two geometry files that serve as an example.
geometry-a1a2.h
geometry-h8g8.h

You would have to look at them and then create one "geometry-a1b1.h". The definitions in kpk.c need no change. Only change the reference to the geometry.h file in kpk.h.

**Comment by kervinck** [comment]
If that doesn't work, feel free to paste your new file here and I take a quick look

**Comment by thorsilver** [comment]
Thank you!  What's confusing me is that with my a1-b1 orientation, the ranks are now like files in your a1-a2 orientation, so my thought was this:

enum file { fileA, fileB, fileC, fileD, fileE, fileF, fileG, fileH };
enum rank { rank1, rank2, rank3, rank4, rank5, rank6, rank7, rank8 };

#define file(square)       ((square) & 7)
#define rank(square)       ((square) >> 3)
#define square(file, rank) ((file) + (rank << 3))

enum square {
    a1, b1, c1, d1, e1, f1, g1, h1,
    a2, b2, c2, d2, e2, f2, g2, h2,
    a3, b3, c3, d3, e3, f3, g3, h3,
    a4, b4, c4, d4, e4, f4, g4, h4,
    a5, b5, c5, d5, e5, f5, g5, h5,
    a6, b6, c6, d6, e6, f6, g6, h6,
    a7, b7, c7, d7, e7, f7, g7, h7,
    a8, b8, c8, d8, e8, f8, g8, h8,
    boardSize
};

But of course it doesn't work, and I'm fairly certain I'm missing a very obvious problem but I can't quite spot it.

**Comment by kervinck** [comment]
I tried it on Ubuntu and got it to pass the selftest with just this change:

```
#define square(file, rank) ((file) + ((rank) << 3))
                                      ^    ^ 
```

Does that help?

(For some reason it fails compilation on my Macbook now, but that must be a configuration-specific problem for OSX.)

**Comment by thorsilver** [comment]
Yep, that works!  Fantastic, thank you so much for your help :)  I knew it would be something fiddly like that.  Now to integrate it into my engine!

Interestingly I'm working on OSX too, but it compiles just fine for me.  I'm using CLion and imported the repo into a CMake project.

**Comment by kervinck** [comment]
Great!
